name: Docker Image CI (Build and push to Docker Hub)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3      
        
    - name: Build and push Docker Image
      uses: docker/build-push-action@v4 
      with:
        image: serhiofateev/demo-ci-cd-repo
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
