name: Docker Image CI (Build and push to Docker Hub)

on: workflow_dispatch

env:
  docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
  docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
jobs: 

  build:
    runs-on: ubuntu-latest   
      
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

        
    - name: Login to Docker Hub
      run:  echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Build image
      run: docker build -t $docker_username/$docker_password:${GITHUB_REF:11} -f Dockerfile .
      
    - name: Push image to Docker Hub
      run: docker push $docker_username/$docker_password:${GITHUB_REF:11}
