name: Docker Image CI (Build and push to Docker Hub)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Docker Hub login
      uses: docker/login-action@v2
      with: 
	username: ${{ secrets.DOCKERHUB_USERNAME }}
 	password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
     - name: Get the version
       id: vars
       run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
	 
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4 
      run: docker build . --file Dockerfile --tag Fazinho/log-py-docker:$
      run: docker push Fazinho/log-py-docker:$
      with:
        image: serhiofateev/demo-ci-cd-repo
        registry: docker.io
