name: Docker Image CI (Build and push to Docker Hub)

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Docker login
      uses: docker/login-action@v2
      with:
        image: serhiofateev/demo-ci-cd-repo 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
